version: '3'

services:
  db:
    image: mysql
    container_name: db
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=123456
    networks:
      - node_network
    volumes:
      - ./mysql:/var/lib/mysql
  app:
    image: fullcycle/nodeapp
    build:
      context: ./app
      dockerfile: Dockerfile.dev
    container_name: app
    restart: always
    tty: true
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=123456
      - DB_NAME=nodeDB
    volumes:
      - ./app/:/app/
    ports:
      - 3000:3000
    networks:
      - node_network
    depends_on:
      - db
    # command: tail -f /dev/null

networks:
  node_network:
    driver: bridge
