version: '3'

services:
  db:
    image: mysql
    container_name: db
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=123456
    networks:
      - node_network
    volumes:
      - ./mysql:/var/lib/mysql
  app:
    build:
      context: ./app
      dockerfile: Dockerfile.dev
    container_name: app
    restart: always
    tty: true
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=123456
      - DB_NAME=nodeDB
    entrypoint: sh -c "npm install && node index.js"
    volumes:
      - ./app/:/app/      
    networks:
      - node_network
    depends_on:
      - db
  nginx:
    build:
      context: ./nginx
    container_name: nginx_app
    restart: always
    ports:
      - 8080:80
    networks:
      - node_network
    depends_on:
      - app

networks:
  node_network:
    driver: bridge
