FROM node:20

WORKDIR /app

VOLUME ["/app"]

EXPOSE 3000

ENV DB_HOST=db
ENV DB_PORT=3306
ENV DB_USER=""
ENV DB_PASSWORD=""
ENV DB_NAME=""

HEALTHCHECK --interval=5s --timeout=5s --retries=20 \
    CMD wget --no-verbose --tries=1 --spider http://localhost:3000/ || exit 1